apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: yyvorb62m-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-9a3a61bdb6.onrq.p3.openshiftapps.com/rhtap/rhtap-qe:a9135777dd4569fe7fcae7073e450a96f853c834@sha256:93642292194e90106f4bb1d1b5ea28aaf730320961106d4d17a150108349de49
        name: container-image  
